"""Initial Migration

Revision ID: d9c7c6f3c932
Revises: 
Create Date: 2023-04-22 00:04:20.216407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c7c6f3c932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rate')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('cart', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['tel'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cart')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('tel')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.SMALLINT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
