"""empty message

Revision ID: f3a734036eab
Revises: d9c7c6f3c932
Create Date: 2023-04-22 21:44:16.775963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a734036eab'
down_revision = 'd9c7c6f3c932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('patronymic', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('patronymic')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
